### ISSUE TITLE
Not adding current directory to sys.path

### ISSUE THREAD

**Issue by hammerheadlemon** [jonathanslenders/ptpython#246] opened 2018-06-06 20:15 UTC
I can't work out why some instances of `ptpython` add the current directory to `sys.path`. Most of my projects to date, using 0.41, do this with no issues, but in recent installations I've noticed that it is missing from `sys.path`. Is there a condition for this I'm missing? I can't do basic imports. Stock `python` (3.6.4) interpreter and `bpython` - as a quick check - add the current directory without an issue. Tested in a variety of virtualenvs. `$PYTHONPATH` not set. Thanks.

**Comment by jonathanslenders** [comment] 2018-06-06 20:57
Hi @hammerheadlemon,

This should happen on the following line: https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptpython.py#L48
Can you check whether this lines appears in your ptpython source and whether it executes this line?

**Comment by hammerheadlemon** [comment] 2018-06-06 21:17
Hi @jonathanslenders - thanks for pitching in so quickly. Have just been looking at this. Running under the debugger is okay - breakpoint hits at [https://github.com/jonathanslenders/ptpython/blob/d00f8d454fe2b94c499869e6677cce7a22601fc4/ptpython/entry_points/run_ptpython.py#L50](url) and `sys.path` is obviously set correctly, here, and running on from here to the repl, I get the correct path, but I guess this is a result of executing using the debugger? Without setting a tracepoint, no `sys.path` is set.

**Comment by hammerheadlemon** [comment] 2018-06-07 06:37
Further investigation...  I am seeing this:

Run `ptpython` as normal and get to the repl:

```python
sys.path
```

Working directory **is** at `sys.path[0]`. Then:

```python
import package

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'package'

No module named 'package'
```

Then:

`sys.path`

Working directory **is not** now in path.

Insert directory manually:

```python
sys.path.insert(0, '')
sys.path
```
Path is there.

```python
import package

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'package'

No module named 'package'
```

```import``` statements appear to remove `sys.path[0]` in this case (when adding an empty string to the path to represent working directory), although I haven't debugged further at this stage.

If I hardcode the working directory:

```python
sys.path.insert(0, '/home/path/to/working/directory')
sys.path
```

Working directory is there. `import` works, `sys.path` stays the same, and correct.

**Comment by SBKch** [comment] 2018-06-17 21:43
Confirming the same problem, current directory path isn't added automatically and it's removed from sys.path if added as '', '.' works though.

**Comment by davidhalter** [comment] 2018-06-18 17:59
This is a Jedi bug. Confirmed in https://github.com/davidhalter/jedi/issues/1148. Sorry for the issues it has caused.

**Comment by jonathanslenders** [comment] 2018-09-30 19:10
Hi everyone, I pushed a new version of ptpython that ensures that the current directory is always present in sys.path. This also upgrades to prompt_toolkit 2.0. Can you try again?

**Comment by davidhalter** [comment] 2018-09-30 23:04
I will probably release a new Jedi version (without major changes, but with the patch for this bug). It has been fixed since 4th of July, but hasn't been released (I forgot to do that).

**Comment by hammerheadlemon** [comment] 2018-10-01 07:37
Thank you @davidhalter and @jonathanslenders . Will download and try in the next few days.

**Comment by jonathanslenders** [comment] 2018-10-13 21:13
Closing this. ptpython has a workaround, and there is a new Jedi release.

**Closed by jonathanslenders** 2018-10-13 21:13 UTC
