### ISSUE TITLE
IndexError: list index out of range in apply_transformation

### ISSUE THREAD

**Issue by kiddick** [jonathanslenders/ptpython#152] opened 2016-11-23 11:04 UTC
How to reproduce:

1. Copy-paste some text with newline(s) in some text editor. Often case with coping from terminal.
ex:
```
ss

```

2. open ptpython
3. open circle bracket
`>>> (`
4. Insert from clipboard
As you can see cursor've moved to beginning of line
![image](https://cloud.githubusercontent.com/assets/9250239/20559432/cf343f9a-b18d-11e6-935e-e0c87137ffc7.png)
5. close circle bracket
6. fail

```
Traceback (most recent call last):
  File "/usr/local/bin/ptpython", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/ptpython/entry_points/run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "/usr/local/lib/python2.7/dist-packages/ptpython/repl.py", line 315, in embed
    cli.run()
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 326, in redraw
    self._redraw()
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/renderer.py", line 436, in render
    extended_height=size.rows,
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 259, in preferred_height
    for s, c in zip(sizes, self.children)]
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/controls.py", line 641, in create_content
    document.cursor_position_col),
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/controls.py", line 623, in translate_rowcol
    return Point(y=row, x=get_processed_line(row).source_to_display(col))
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/controls.py", line 583, in get_processed_line
    processed_line = transform(i, get_line(i))
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/controls.py", line 559, in transform
    cli, document, lineno, source_to_display, tokens)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/processors.py", line 554, in apply_transformation
    cli, document, lineno, source_to_display, tokens)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/processors.py", line 255, in apply_transformation
    token, text = tokens[col]
IndexError: list index out of range
```

**Comment by jonathanslenders** [comment] 2016-11-23 19:48
Hi @kiddick,

Thanks for reporting this issue! Unfortunately, I'm not able to reproduce it right now.
Could you tell me which version of ptpython and prompt_toolkit you are running? (Type `` pip freeze ``.)

Thanks!

**Comment by kiddick** [comment] 2016-11-29 14:26
```
ptpython==0.35
prompt-toolkit==1.0.5

**Comment by kiddick** [comment] 2016-11-29 14:29
I've updated ptpyhon to 0.36 and seems everything is ok. And I can't reproduce it too :)

**Comment by jonathanslenders** [comment] 2016-11-29 22:12
That's good to hear!
So, I'm closing this issue. Don't hesitate to open again or create a new issue if you notice further problems.

**Closed by jonathanslenders** 2016-11-29 22:12 UTC
Labels: bug
